class Problem29 < Problem
  def self.title
    "How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?"
  end

  def self.solve
    terms = {}
    (2..100).each do |n|
      power = n
      99.times do
        power *= n
        terms[power] = true
      end
    end
    terms.length
  end
end
